<?php

namespace AppBundle\Repository;

/**
 * defaultmaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class defaultmaterialRepository extends \Doctrine\ORM\EntityRepository
{
}
