<?php

namespace AppBundle\Repository;

/**
 * GroupAttributesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupAttributesRepository extends \Doctrine\ORM\EntityRepository
{
}
