<?php

namespace AppBundle\Repository;

/**
 * ProdtypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdtypeRepository extends \Doctrine\ORM\EntityRepository
{
}
