<?php

namespace AppBundle\Repository;

/**
 * ProdgroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdgroupRepository extends \Doctrine\ORM\EntityRepository
{
}
