<?php

namespace AppBundle\Repository;

/**
 * PurchaseorderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseorderRepository extends \Doctrine\ORM\EntityRepository
{
}
