app:
    resource: '@AppBundle/Controller/'
    type: annotation

api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api' # Optional
    
homepage:
    path: '@AppBundle/Controller/'    
    defaults:
        _controller: 'MainController'
       
    
